/**
 * Living Documentation System
 * 
 * Auto-updating documentation, API generation, and automated changelogs
 */

import { invokeLLM } from "../_core/llm";
import * as fs from "fs/promises";
import * as path from "path";

export interface DocumentationSection {
  title: string;
  content: string;
  lastUpdated: Date;
  autoGenerated: boolean;
  sourceFiles: string[];
}

export interface APIEndpoint {
  method: string;
  path: string;
  description: string;
  parameters: Array<{ name: string; type: string; required: boolean; description: string }>;
  responses: Array<{ status: number; description: string; schema?: any }>;
  examples: Array<{ request: any; response: any }>;
}

export interface ChangelogEntry {
  version: string;
  date: Date;
  changes: Array<{
    type: "feature" | "bugfix" | "breaking" | "improvement" | "deprecation";
    description: string;
    pr?: string;
    author?: string;
  }>;
}

/**
 * Generate documentation from source code
 */
export async function generateDocumentation(
  sourceFiles: string[],
  outputPath: string
): Promise<{ success: boolean; sectionsGenerated: number }> {
  console.log(`[Living Documentation] Generating documentation from ${sourceFiles.length} files...`);

  const sections: DocumentationSection[] = [];

  for (const filePath of sourceFiles) {
    try {
      const content = await fs.readFile(filePath, "utf-8");
      const section = await generateSectionFromCode(filePath, content);
      sections.push(section);
    } catch (error: any) {
      console.error(`Failed to process ${filePath}:`, error.message);
    }
  }

  // Combine sections into a single markdown document
  const markdown = sections
    .map((section) => `## ${section.title}\n\n${section.content}\n\n---\n`)
    .join("\n");

  // Write to output file
  await fs.writeFile(outputPath, markdown, "utf-8");

  return {
    success: true,
    sectionsGenerated: sections.length,
  };
}

/**
 * Generate a documentation section from code
 */
async function generateSectionFromCode(
  filePath: string,
  code: string
): Promise<DocumentationSection> {
  const fileName = path.basename(filePath);

  const prompt = `Generate comprehensive documentation for this code file.

**File:** ${fileName}

**Code:**
\`\`\`
${code}
\`\`\`

Create documentation that includes:
1. Overview of what this file does
2. Key functions/classes and their purpose
3. Usage examples
4. Important notes or caveats

Write in clear, professional markdown format.

Respond in JSON format:
{
  "title": "section title",
  "content": "markdown documentation content"
}`;

  const response = await invokeLLM({
    messages: [
      { role: "system", content: "You are an expert technical writer creating clear, comprehensive documentation." },
      { role: "user", content: prompt },
    ],
    response_format: {
      type: "json_schema",
      json_schema: {
        name: "documentation_section",
        strict: true,
        schema: {
          type: "object",
          properties: {
            title: { type: "string" },
            content: { type: "string" },
          },
          required: ["title", "content"],
          additionalProperties: false,
        },
      },
    },
  });

  const result = JSON.parse((typeof response.choices[0].message.content === "string" ? response.choices[0].message.content : JSON.stringify(response.choices[0].message.content)) || "{}");

  return {
    title: result.title,
    content: result.content,
    lastUpdated: new Date(),
    autoGenerated: true,
    sourceFiles: [filePath],
  };
}

/**
 * Generate API documentation from tRPC routers
 */
export async function generateAPIDocumentation(
  routerFiles: string[]
): Promise<APIEndpoint[]> {
  console.log(`[Living Documentation] Generating API docs from ${routerFiles.length} routers...`);

  const endpoints: APIEndpoint[] = [];

  for (const filePath of routerFiles) {
    try {
      const content = await fs.readFile(filePath, "utf-8");
      const fileEndpoints = await extractEndpointsFromRouter(filePath, content);
      endpoints.push(...fileEndpoints);
    } catch (error: any) {
      console.error(`Failed to process ${filePath}:`, error.message);
    }
  }

  return endpoints;
}

/**
 * Extract API endpoints from a router file
 */
async function extractEndpointsFromRouter(
  filePath: string,
  code: string
): Promise<APIEndpoint[]> {
  const prompt = `Analyze this tRPC router file and extract all API endpoints.

**File:** ${filePath}

**Code:**
\`\`\`typescript
${code}
\`\`\`

For each endpoint, extract:
1. Method type (query or mutation)
2. Path (e.g., "user.getProfile")
3. Description
4. Input parameters
5. Response structure
6. Example request/response

Respond in JSON format:
{
  "endpoints": [
    {
      "method": "query",
      "path": "user.getProfile",
      "description": "Get user profile",
      "parameters": [
        {"name": "userId", "type": "string", "required": true, "description": "User ID"}
      ],
      "responses": [
        {"status": 200, "description": "Success", "schema": {}}
      ],
      "examples": [
        {"request": {}, "response": {}}
      ]
    }
  ]
}`;

  const response = await invokeLLM({
    messages: [
      { role: "system", content: "You are an expert at analyzing code and generating API documentation." },
      { role: "user", content: prompt },
    ],
    response_format: {
      type: "json_schema",
      json_schema: {
        name: "api_endpoints",
        strict: true,
        schema: {
          type: "object",
          properties: {
            endpoints: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  method: { type: "string" },
                  path: { type: "string" },
                  description: { type: "string" },
                  parameters: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        name: { type: "string" },
                        type: { type: "string" },
                        required: { type: "boolean" },
                        description: { type: "string" },
                      },
                      required: ["name", "type", "required", "description"],
                      additionalProperties: false,
                    },
                  },
                  responses: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        status: { type: "number" },
                        description: { type: "string" },
                      },
                      required: ["status", "description"],
                      additionalProperties: false,
                    },
                  },
                  examples: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {},
                      additionalProperties: true,
                    },
                  },
                },
                required: ["method", "path", "description", "parameters", "responses", "examples"],
                additionalProperties: false,
              },
            },
          },
          required: ["endpoints"],
          additionalProperties: false,
        },
      },
    },
  });

  const result = JSON.parse((typeof response.choices[0].message.content === "string" ? response.choices[0].message.content : JSON.stringify(response.choices[0].message.content)) || "{}");
  return result.endpoints || [];
}

/**
 * Generate changelog from Git commits
 */
export async function generateChangelog(
  commits: Array<{ hash: string; message: string; author: string; date: Date }>,
  currentVersion: string
): Promise<ChangelogEntry> {
  const prompt = `Analyze these Git commits and generate a changelog entry.

**Version:** ${currentVersion}

**Commits:**
${commits.map((c) => `- ${c.message} (${c.author})`).join("\n")}

Categorize each commit as:
- feature: New features
- bugfix: Bug fixes
- breaking: Breaking changes
- improvement: Improvements to existing features
- deprecation: Deprecated features

Respond in JSON format:
{
  "changes": [
    {
      "type": "feature",
      "description": "Added new feature X",
      "author": "John Doe"
    }
  ]
}`;

  const response = await invokeLLM({
    messages: [
      { role: "system", content: "You are an expert at analyzing Git commits and generating changelogs." },
      { role: "user", content: prompt },
    ],
    response_format: {
      type: "json_schema",
      json_schema: {
        name: "changelog_entry",
        strict: true,
        schema: {
          type: "object",
          properties: {
            changes: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  type: {
                    type: "string",
                    enum: ["feature", "bugfix", "breaking", "improvement", "deprecation"],
                  },
                  description: { type: "string" },
                  author: { type: "string" },
                },
                required: ["type", "description"],
                additionalProperties: false,
              },
            },
          },
          required: ["changes"],
          additionalProperties: false,
        },
      },
    },
  });

  const result = JSON.parse((typeof response.choices[0].message.content === "string" ? response.choices[0].message.content : JSON.stringify(response.choices[0].message.content)) || "{}");

  return {
    version: currentVersion,
    date: new Date(),
    changes: result.changes || [],
  };
}

/**
 * Update documentation based on code changes
 */
export async function updateDocumentation(
  changedFiles: string[],
  documentationPath: string
): Promise<{ success: boolean; sectionsUpdated: number }> {
  console.log(`[Living Documentation] Updating documentation for ${changedFiles.length} changed files...`);

  // Read existing documentation
  let existingDocs = "";
  try {
    existingDocs = await fs.readFile(documentationPath, "utf-8");
  } catch (error) {
    // File doesn't exist yet, will create new
  }

  // Generate new sections for changed files
  const updatedSections: DocumentationSection[] = [];

  for (const filePath of changedFiles) {
    try {
      const content = await fs.readFile(filePath, "utf-8");
      const section = await generateSectionFromCode(filePath, content);
      updatedSections.push(section);
    } catch (error: any) {
      console.error(`Failed to process ${filePath}:`, error.message);
    }
  }

  // Merge with existing docs
  // TODO: Implement smart merging logic

  // Write updated documentation
  const markdown = updatedSections
    .map((section) => `## ${section.title}\n\n${section.content}\n\n---\n`)
    .join("\n");

  await fs.writeFile(documentationPath, existingDocs + "\n\n" + markdown, "utf-8");

  return {
    success: true,
    sectionsUpdated: updatedSections.length,
  };
}
